version: '3.4'

networks:
  ChallengeMeliNetwork:
services:
  challengemeli:
    image: ${DOCKER_REGISTRY-}challengemeli
    build:
      context: .
      dockerfile: src/Presentation/Dockerfile
    networks:
      - ChallengeMeliNetwork
    depends_on:
      - redis-cluster

  redis-cluster:
    image: docker.io/grokzen/redis-cluster:latest
    ports:
      - "6379-6399:6379-6399"
    environment:
      - INITIAL_PORT=6379
      - IP=0.0.0.0
    networks:
      - ChallengeMeliNetwork